export { default as MainPage } from './MainPage/MainPage';
export { default as NotFoundPage } from './NotFoundPage/NotFoundPage';
export { default as RegistrationPage } from './RegistrationPage/RegistrationPage';
export { default as SingUpPage } from './SignUpPage/SignUpPage';
export { default as SingInPage } from './SignInPage/SignInPage';
export { default as SearchPage } from './SearchPage/SearchPage';
export { default as BoardsPage } from './BoardsPage/BoardsPage';
export { default as ProfilePage } from './ProfilePage/ProfilePage';
export { default as TasksPage } from './TasksPage/TasksPage';
